/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ControleCliente;
import controle.ControleTelefone;
import java.util.ArrayList;
import modelo.ModeloCliente;

/**
 *
 * @author fredw
 */
public class FrmCliente extends javax.swing.JFrame {

    ControleCliente controleCliente = new ControleCliente();
    ControleTelefone controleTelefone = new ControleTelefone();
    ModeloCliente modeloCliente = new ModeloCliente();
    int navegando;
    boolean cadastroNovo;

    /**
     * Creates new form FrmCliente
     */
    public FrmCliente() {
        initComponents();

    }

    private void preencherComboEstados() {
        ArrayList nomesEstados = controleCliente.devolverNomesEstados();
        int numeroAtual = 0;
        jComboBoxEstado.removeAllItems();
        do {
            jComboBoxEstado.addItem(nomesEstados.get(numeroAtual));
            numeroAtual = ++numeroAtual;
        } while (nomesEstados.size() > numeroAtual);
    }

    private void preencherComboCidades(int id_Estado) {
        ArrayList nomesCidades = controleCliente.devolverNomesCidades(id_Estado);
        int numeroAtual = 0;
        jComboBoxCidade.removeAllItems();
        do {
            jComboBoxCidade.addItem(nomesCidades.get(numeroAtual));
            numeroAtual = ++numeroAtual;
        } while (nomesCidades.size() > numeroAtual);
    }

    private void preencherComboBairros(int id_Cidade) {
        ArrayList nomesBairros = controleCliente.devolverNomesBairros(id_Cidade);
        int numeroAtual = 0;
        jComboBoxBairro.removeAllItems();
        do {
            jComboBoxBairro.addItem(nomesBairros.get(numeroAtual));
            numeroAtual = ++numeroAtual;
        } while (nomesBairros.size() > numeroAtual);
    }

    private void preencherComboTelefonePorCliente(int id_cliente) {
        ArrayList numerosTelefone = controleTelefone.preencherComboTelefonePorCliente(id_cliente);
        int numeroAtual = 0;
        jComboBoxTelefone.removeAllItems();
        jComboBoxTelefone.setEnabled(true);
        if (!numerosTelefone.isEmpty()) {
            do {
                jComboBoxTelefone.addItem(numerosTelefone.get(numeroAtual));
                numeroAtual = ++numeroAtual;
            } while (numerosTelefone.size() > numeroAtual);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxTelefone = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldRG = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxCidade = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxBairro = new javax.swing.JComboBox();
        jButtonNovo = new javax.swing.JButton();
        jButtonCadastraEstado = new javax.swing.JButton();
        jButtonCadastraCidade = new javax.swing.JButton();
        jButtonCadastraBairro = new javax.swing.JButton();
        jButtonCadastrarTelefone = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonUltimo = new javax.swing.JButton();
        jButtonPrimeiro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario de cadastro de clientes");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Codigo:");

        jTextFieldCodigo.setEditable(false);

        jLabel3.setText("Nome:");

        jTextFieldNome.setEditable(false);

        jLabel4.setText("Telefone:");

        jComboBoxTelefone.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTelefone.setEnabled(false);

        jLabel5.setText("Endereço:");

        jTextFieldEndereco.setEditable(false);

        jLabel6.setText("RG:");

        jLabel7.setText("CPF:");

        jFormattedTextFieldRG.setEditable(false);

        jFormattedTextFieldCPF.setEditable(false);

        jLabel8.setText("Estado:");

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEstado.setEnabled(false);
        jComboBoxEstado.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxEstadoPopupMenuWillBecomeVisible(evt);
            }
        });

        jLabel9.setText("Cidade:");

        jComboBoxCidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCidade.setEnabled(false);
        jComboBoxCidade.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxCidadePopupMenuWillBecomeVisible(evt);
            }
        });

        jLabel10.setText("Bairro:");

        jComboBoxBairro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxBairro.setEnabled(false);
        jComboBoxBairro.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxBairroPopupMenuWillBecomeVisible(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonCadastraEstado.setText("...");
        jButtonCadastraEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastraEstadoActionPerformed(evt);
            }
        });

        jButtonCadastraCidade.setText("...");
        jButtonCadastraCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastraCidadeActionPerformed(evt);
            }
        });

        jButtonCadastraBairro.setText("...");
        jButtonCadastraBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastraBairroActionPerformed(evt);
            }
        });

        jButtonCadastrarTelefone.setText("...");
        jButtonCadastrarTelefone.setEnabled(false);
        jButtonCadastrarTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarTelefoneActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonDeletar.setText("Deletar");
        jButtonDeletar.setEnabled(false);
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonProximo.setText("Proximo");
        jButtonProximo.setEnabled(false);
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jButtonAnterior.setText("Anterior");
        jButtonAnterior.setEnabled(false);
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonUltimo.setText("Ultimo");
        jButtonUltimo.setEnabled(false);
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });

        jButtonPrimeiro.setText("Primeiro");
        jButtonPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroActionPerformed(evt);
            }
        });

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableClientes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTelefone, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCadastrarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFormattedTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldEndereco))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonNovo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonSalvar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonEditar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonDeletar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonCancelar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonPrimeiro)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonUltimo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonAnterior)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonProximo))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonCadastraEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonCadastraCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonCadastraBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadastrarTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jFormattedTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadastraEstado)
                    .addComponent(jButtonCadastraCidade)
                    .addComponent(jButtonCadastraBairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonDeletar)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonProximo)
                    .addComponent(jButtonAnterior)
                    .addComponent(jButtonUltimo)
                    .addComponent(jButtonPrimeiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBoxTelefone.removeAllItems();
        jComboBoxEstado.removeAllItems();
        jComboBoxCidade.removeAllItems();
        jComboBoxBairro.removeAllItems();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        jTextFieldNome.setEditable(true);
        jFormattedTextFieldRG.setEditable(true);
        jFormattedTextFieldCPF.setEditable(true);
        jTextFieldEndereco.setEditable(true);
        jTextFieldNome.requestFocus();
        jComboBoxEstado.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonPrimeiro.setEnabled(false);
        jButtonUltimo.setEnabled(false);
        jButtonProximo.setEnabled(false);
        jButtonAnterior.setEnabled(false);
        jFormattedTextFieldRG.setText(null);
        jFormattedTextFieldCPF.setText(null);
        jTextFieldEndereco.setText(null);
        jComboBoxEstado.removeAllItems();
        jComboBoxCidade.removeAllItems();
        jComboBoxBairro.removeAllItems();
        jComboBoxTelefone.removeAllItems();
        jComboBoxTelefone.setEnabled(false);
        jTextFieldNome.setText(null);
        jTextFieldCodigo.setText(null);
        navegando = 0;
        jButtonDeletar.setEnabled(false);
        cadastroNovo = true;
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jComboBoxEstadoPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxEstadoPopupMenuWillBecomeVisible
        if (navegando != 1) {
            preencherComboEstados();
            jComboBoxCidade.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBoxEstadoPopupMenuWillBecomeVisible

    private void jComboBoxCidadePopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxCidadePopupMenuWillBecomeVisible
        if (navegando != 1) {
            int id_Estado = controleCliente.retornaIdEstado("" + jComboBoxEstado.getSelectedItem() + "");
            preencherComboCidades(id_Estado);
            jComboBoxBairro.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBoxCidadePopupMenuWillBecomeVisible

    private void jComboBoxBairroPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxBairroPopupMenuWillBecomeVisible
        if (navegando != 1) {
            int id_Cidade = controleCliente.retornaIdCidade("" + jComboBoxCidade.getSelectedItem() + "");
            preencherComboBairros(id_Cidade);
        }
    }//GEN-LAST:event_jComboBoxBairroPopupMenuWillBecomeVisible

    private void jButtonCadastraEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastraEstadoActionPerformed
        FrmEstado frmEstado = new FrmEstado();
        frmEstado.setVisible(true);


    }//GEN-LAST:event_jButtonCadastraEstadoActionPerformed

    private void jButtonCadastraCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastraCidadeActionPerformed
        FrmCidade frmCidade = new FrmCidade();
        frmCidade.setVisible(true);
    }//GEN-LAST:event_jButtonCadastraCidadeActionPerformed

    private void jButtonCadastraBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastraBairroActionPerformed
        FrmBairro frmBairro = new FrmBairro();
        frmBairro.setVisible(true);
    }//GEN-LAST:event_jButtonCadastraBairroActionPerformed

    private void jButtonCadastrarTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarTelefoneActionPerformed
        FrmTelefone frmTelefone = new FrmTelefone();
        frmTelefone.id_cliente = modeloCliente.getId_Cliente();
        frmTelefone.setModal(true);
        frmTelefone.setVisible(true);
        preencherComboTelefonePorCliente(modeloCliente.getId_Cliente());
    }//GEN-LAST:event_jButtonCadastrarTelefoneActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        modeloCliente.setNome_Cliente(jTextFieldNome.getText());
        modeloCliente.setRg_Clinete(jFormattedTextFieldRG.getText());
        modeloCliente.setCpf_Cliente(jFormattedTextFieldCPF.getText());
        modeloCliente.setEndereco_Cliente(jTextFieldEndereco.getText());
        modeloCliente.setId_Bairro(controleCliente.retornaIdBairro("" + jComboBoxBairro.getSelectedItem() + ""));
        modeloCliente.setId_cidade(controleCliente.retornaIdCidade("" + jComboBoxCidade.getSelectedItem() + ""));
        if (cadastroNovo) {
            controleCliente.inserirCliente(modeloCliente);
        } else {
            modeloCliente.setId_Cliente(Integer.parseInt(jTextFieldCodigo.getText()));
            controleCliente.editarCliente(modeloCliente);
        }
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonPrimeiro.setEnabled(true);
        jTextFieldNome.setEditable(false);
        jTextFieldNome.setText(null);
        jFormattedTextFieldRG.setEditable(false);
        jFormattedTextFieldRG.setText(null);
        jFormattedTextFieldCPF.setEditable(false);
        jFormattedTextFieldCPF.setText(null);
        jTextFieldEndereco.setEditable(false);
        jTextFieldEndereco.setText(null);
        jComboBoxEstado.setEnabled(false);
        jComboBoxEstado.removeAllItems();
        jComboBoxCidade.setEnabled(false);
        jComboBoxCidade.removeAllItems();
        jComboBoxBairro.setEnabled(false);
        jComboBoxBairro.removeAllItems();
        jTableClientes.setModel(controleCliente.preencherTabelaCliente());
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroActionPerformed
        modeloCliente = controleCliente.navergarBancoCliente("primeiro");
        jTextFieldCodigo.setText(String.valueOf(modeloCliente.getId_Cliente()));
        preencherComboTelefonePorCliente(modeloCliente.getId_Cliente());
        jTextFieldNome.setText(modeloCliente.getNome_Cliente());
        jTextFieldEndereco.setText(modeloCliente.getEndereco_Cliente());
        jFormattedTextFieldRG.setText(modeloCliente.getRg_Clinete());
        jFormattedTextFieldCPF.setText(modeloCliente.getCpf_Cliente());
        jComboBoxBairro.removeAllItems();
        jComboBoxCidade.removeAllItems();
        jComboBoxEstado.removeAllItems();
        jComboBoxBairro.addItem(modeloCliente.getNome_bairro());
        jComboBoxCidade.addItem(modeloCliente.getNome_cidade());
        jComboBoxEstado.addItem(modeloCliente.getNome_estado());
        jButtonUltimo.setEnabled(true);
        jButtonProximo.setEnabled(true);
        jButtonAnterior.setEnabled(true);
        jButtonCadastrarTelefone.setEnabled(true);
        navegando = 1;
        jComboBoxEstado.setEnabled(true);
        jComboBoxCidade.setEnabled(true);
        jComboBoxBairro.setEnabled(true);
        jButtonDeletar.setEnabled(true);
        jButtonEditar.setEnabled(true);

    }//GEN-LAST:event_jButtonPrimeiroActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        modeloCliente = controleCliente.navergarBancoCliente("ultimo");
        jTextFieldCodigo.setText(String.valueOf(modeloCliente.getId_Cliente()));
        preencherComboTelefonePorCliente(modeloCliente.getId_Cliente());
        jTextFieldNome.setText(modeloCliente.getNome_Cliente());
        jTextFieldEndereco.setText(modeloCliente.getEndereco_Cliente());
        jFormattedTextFieldRG.setText(modeloCliente.getRg_Clinete());
        jFormattedTextFieldCPF.setText(modeloCliente.getCpf_Cliente());
        jComboBoxBairro.removeAllItems();
        jComboBoxCidade.removeAllItems();
        jComboBoxEstado.removeAllItems();
        jComboBoxBairro.addItem(modeloCliente.getNome_bairro());
        jComboBoxCidade.addItem(modeloCliente.getNome_cidade());
        jComboBoxEstado.addItem(modeloCliente.getNome_estado());

    }//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        modeloCliente = controleCliente.navergarBancoCliente("anterior");
        jTextFieldCodigo.setText(String.valueOf(modeloCliente.getId_Cliente()));
        preencherComboTelefonePorCliente(modeloCliente.getId_Cliente());
        jTextFieldNome.setText(modeloCliente.getNome_Cliente());
        jTextFieldEndereco.setText(modeloCliente.getEndereco_Cliente());
        jFormattedTextFieldRG.setText(modeloCliente.getRg_Clinete());
        jFormattedTextFieldCPF.setText(modeloCliente.getCpf_Cliente());
        jComboBoxBairro.removeAllItems();
        jComboBoxCidade.removeAllItems();
        jComboBoxEstado.removeAllItems();
        jComboBoxBairro.addItem(modeloCliente.getNome_bairro());
        jComboBoxCidade.addItem(modeloCliente.getNome_cidade());
        jComboBoxEstado.addItem(modeloCliente.getNome_estado());

    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        modeloCliente = controleCliente.navergarBancoCliente("proximo");
        jTextFieldCodigo.setText(String.valueOf(modeloCliente.getId_Cliente()));
        preencherComboTelefonePorCliente(modeloCliente.getId_Cliente());
        jTextFieldNome.setText(modeloCliente.getNome_Cliente());
        jTextFieldEndereco.setText(modeloCliente.getEndereco_Cliente());
        jFormattedTextFieldRG.setText(modeloCliente.getRg_Clinete());
        jFormattedTextFieldCPF.setText(modeloCliente.getCpf_Cliente());
        jComboBoxBairro.removeAllItems();
        jComboBoxCidade.removeAllItems();
        jComboBoxEstado.removeAllItems();
        jComboBoxBairro.addItem(modeloCliente.getNome_bairro());
        jComboBoxCidade.addItem(modeloCliente.getNome_cidade());
        jComboBoxEstado.addItem(modeloCliente.getNome_estado());

    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonPrimeiro.setEnabled(true);
        jTextFieldNome.setEditable(false);
        jTextFieldNome.setText(null);
        jFormattedTextFieldRG.setEditable(false);
        jFormattedTextFieldRG.setText(null);
        jFormattedTextFieldCPF.setEditable(false);
        jFormattedTextFieldCPF.setText(null);
        jTextFieldEndereco.setEditable(false);
        jTextFieldEndereco.setText(null);
        jComboBoxEstado.setEnabled(false);
        jComboBoxEstado.removeAllItems();
        jComboBoxCidade.setEnabled(false);
        jComboBoxCidade.removeAllItems();
        jComboBoxBairro.setEnabled(false);
        jComboBoxBairro.removeAllItems();
        jComboBoxTelefone.removeAllItems();
        jComboBoxTelefone.setEnabled(false);
        jButtonDeletar.setEnabled(false);
        jButtonEditar.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
        controleCliente.deletarCliente(modeloCliente);
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonPrimeiro.setEnabled(true);
        jTextFieldCodigo.setText(null);
        jTextFieldNome.setEditable(false);
        jTextFieldNome.setText(null);
        jFormattedTextFieldRG.setEditable(false);
        jFormattedTextFieldRG.setText(null);
        jFormattedTextFieldCPF.setEditable(false);
        jFormattedTextFieldCPF.setText(null);
        jTextFieldEndereco.setEditable(false);
        jTextFieldEndereco.setText(null);
        jComboBoxEstado.setEnabled(false);
        jComboBoxEstado.removeAllItems();
        jComboBoxCidade.setEnabled(false);
        jComboBoxCidade.removeAllItems();
        jComboBoxBairro.setEnabled(false);
        jComboBoxBairro.removeAllItems();
        jComboBoxTelefone.removeAllItems();
        jComboBoxTelefone.setEnabled(false);
        jButtonAnterior.setEnabled(false);
        jButtonUltimo.setEnabled(false);
        jButtonProximo.setEnabled(false);
        jButtonDeletar.setEnabled(false);
        jTableClientes.setModel(controleCliente.preencherTabelaCliente());


    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        cadastroNovo = false;
        jTextFieldNome.setEditable(true);
        jFormattedTextFieldRG.setEditable(true);
        jFormattedTextFieldCPF.setEditable(true);
        jTextFieldEndereco.setEditable(true);
        jTextFieldNome.requestFocus();
        jComboBoxEstado.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        navegando = 0;
        jButtonDeletar.setEnabled(false);
        jButtonAnterior.setEnabled(false);
        jButtonUltimo.setEnabled(false);
        jButtonProximo.setEnabled(false);
        jButtonPrimeiro.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jComboBoxTelefone.setEnabled(false);
        jButtonCadastrarTelefone.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        jTableClientes.setModel(controleCliente.preencherTabelaCliente());
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonCadastraBairro;
    private javax.swing.JButton jButtonCadastraCidade;
    private javax.swing.JButton jButtonCadastraEstado;
    private javax.swing.JButton jButtonCadastrarTelefone;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPrimeiro;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JComboBox jComboBoxBairro;
    private javax.swing.JComboBox jComboBoxCidade;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JComboBox jComboBoxTelefone;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldRG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
